name: ValidationPlugin
main: com.example.bukkitspringvalidate.ValidationPlugin
version: 1.0.0
api-version: 1.20
depend: [BukkitSpring]
commands:
  bscheck:
    description: Validate BukkitSpring DI features
    usage: /bscheck
